import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

function History() {
  const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5000';
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedAttempt, setSelectedAttempt] = useState(null);
  const [filterCategory, setFilterCategory] = useState('All');
  const [filterScore, setFilterScore] = useState('All');
  const navigate = useNavigate();

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) {
      navigate('/login');
      return;
    }

    const fetchHistory = async () => {
      try {
        const response = await fetch(`${API_BASE}/api/answers/my`, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        if (response.ok) {
          const data = await response.json();
          // Sort history by date descending
          const sorted = data.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
          setHistory(sorted);
        } else if (response.status === 401) {
          localStorage.removeItem('token');
          navigate('/login');
        }
      } catch (error) {
        console.error("Failed to load history", error);
      } finally {
        setLoading(false);
      }
    };

    fetchHistory();
  }, [navigate]);

  // Apply filters
  const filteredHistory = history.filter(item => {
    // Category Filter
    if (filterCategory !== 'All') {
      if (item.questionId?.category?.toLowerCase() !== filterCategory.toLowerCase()) {
        return false;
      }
    }

    // Score Filter
    if (filterScore !== 'All') {
      const score = item.feedback?.overallScore;
      if (score === undefined || score === null) return false;

      if (filterScore === 'Great' && score < 8) return false;
      if (filterScore === 'Good' && (score < 5 || score >= 8)) return false;
      if (filterScore === 'Needs Work' && score >= 5) return false;
    }

    return true;
  });

  return (
    <div className="transition-fade">
      {/* Title */}
      <div className="mb-6">
        <h1 style={{ fontSize: '32px', margin: '0 0 6px 0', fontWeight: '800' }}>
          Interview <span className="text-gradient">History Log</span>
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '15px', margin: 0 }}>
          Review all your previous practice attempts, scores, and details of the feedback generated by AI.
        </p>
      </div>

      {/* Filter Row */}
      <div className="glass-panel mb-6" style={{ padding: '20px', display: 'flex', gap: '20px', flexWrap: 'wrap' }}>
        <div style={{ flex: 1, minWidth: '150px' }}>
          <label style={{ fontSize: '12px' }}>FILTER BY CATEGORY</label>
          <select 
            value={filterCategory} 
            onChange={(e) => setFilterCategory(e.target.value)}
            style={{ fontSize: '14px', padding: '8px 12px' }}
          >
            <option value="All">All Categories</option>
            <option value="DSA">Data Structures & Algos (DSA)</option>
            <option value="System Design">System Design</option>
            <option value="Behavioral">Behavioral</option>
          </select>
        </div>

        <div style={{ flex: 1, minWidth: '150px' }}>
          <label style={{ fontSize: '12px' }}>FILTER BY SCORE</label>
          <select 
            value={filterScore} 
            onChange={(e) => setFilterScore(e.target.value)}
            style={{ fontSize: '14px', padding: '8px 12px' }}
          >
            <option value="All">All Scores</option>
            <option value="Great">Excellent (Score &ge; 8)</option>
            <option value="Good">Good (Score 5 - 7)</option>
            <option value="Needs Work">Needs Work (Score &lt; 5)</option>
          </select>
        </div>
      </div>

      {/* History Table Container */}
      <div className="glass-panel">
        {loading ? (
          <p style={{ textAlign: 'center', padding: '30px 0', color: 'var(--text-muted)' }}>Loading your attempts...</p>
        ) : filteredHistory.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '40px 0', color: 'var(--text-muted)' }}>
            <span style={{ fontSize: '48px', display: 'block', marginBottom: '12px' }}>📅</span>
            <p style={{ margin: '0 0 16px 0', fontWeight: '500' }}>No matching interview attempts found.</p>
            <button className="btn-primary" onClick={() => navigate('/app/dashboard')}>
              Start Practice Session
            </button>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table>
              <thead>
                <tr>
                  <th>Question</th>
                  <th>Category</th>
                  <th>Difficulty</th>
                  <th>Date Attempted</th>
                  <th>Overall Score</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredHistory.map((item) => (
                  <tr 
                    key={item._id} 
                    className="interactive-row" 
                    onClick={() => setSelectedAttempt(item)}
                  >
                    <td style={{ fontWeight: '600' }}>{item.questionId?.title || 'Unknown Question'}</td>
                    <td>
                      <span className={`badge badge-${item.questionId?.category?.toLowerCase().split(' ')[0]}`}>
                        {item.questionId?.category || 'General'}
                      </span>
                    </td>
                    <td>
                      <span className={`badge badge-${item.questionId?.difficulty?.toLowerCase()}`}>
                        {item.questionId?.difficulty || 'Medium'}
                      </span>
                    </td>
                    <td style={{ color: 'var(--text-muted)' }}>
                      {new Date(item.createdAt).toLocaleString(undefined, { 
                        month: 'short', 
                        day: 'numeric', 
                        year: 'numeric',
                        hour: '2-digit', 
                        minute: '2-digit' 
                      })}
                    </td>
                    <td style={{ fontWeight: '800', fontSize: '15px' }} className={item.feedback?.overallScore >= 7.5 ? 'text-success' : item.feedback?.overallScore >= 5.5 ? '' : 'text-danger'}>
                      {item.feedback?.overallScore ?? 'N/A'}/10
                    </td>
                    <td style={{ textAlign: 'right' }}>
                      <button 
                        className="btn-secondary" 
                        style={{ padding: '6px 12px', fontSize: '12px' }}
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedAttempt(item);
                        }}
                      >
                        View Report
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Modal Overlay for Detailed Review */}
      {selectedAttempt && (
        <div className="modal-overlay" onClick={() => setSelectedAttempt(null)}>
          <div className="modal-container" onClick={(e) => e.stopPropagation()}>
            <div className="glass-panel" style={{ maxHeight: '90vh', overflowY: 'auto', padding: '30px' }}>
              
              {/* Modal Header */}
              <div className="flex-between mb-4" style={{ borderBottom: '1px solid var(--glass-border)', paddingBottom: '16px' }}>
                <div>
                  <span className={`badge badge-${selectedAttempt.questionId?.category?.toLowerCase().split(' ')[0]}`} style={{ marginRight: '8px' }}>
                    {selectedAttempt.questionId?.category}
                  </span>
                  <span className={`badge badge-${selectedAttempt.questionId?.difficulty?.toLowerCase()}`}>
                    {selectedAttempt.questionId?.difficulty}
                  </span>
                  <h3 style={{ fontSize: '20px', margin: '8px 0 4px 0', color: 'white' }}>
                    {selectedAttempt.questionId?.title}
                  </h3>
                  <p style={{ margin: 0, fontSize: '12px', color: 'var(--text-muted)' }}>
                    Practiced on {new Date(selectedAttempt.createdAt).toLocaleString()}
                  </p>
                </div>
                
                {/* SVG Progress Gauge */}
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                  <div className="score-gauge-ring">
                    <svg width="70" height="70" viewBox="0 0 100 100" style={{ transform: 'rotate(-90deg)' }}>
                      <circle cx="50" cy="50" r="42" stroke="rgba(255,255,255,0.04)" strokeWidth="10" fill="transparent" />
                      <circle 
                        cx="50" 
                        cy="50" 
                        r="42" 
                        stroke="var(--primary-glow)" 
                        strokeWidth="10" 
                        fill="transparent"
                        strokeDasharray="263.89" 
                        strokeDashoffset={263.89 - (263.89 * (selectedAttempt.feedback?.overallScore || 0)) / 10}
                        strokeLinecap="round" 
                      />
                    </svg>
                    <div className="score-gauge-val" style={{ color: 'white', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                      <span style={{ fontSize: '18px', fontWeight: '800', lineHeight: 1 }}>{selectedAttempt.feedback?.overallScore || 0}</span>
                      <span style={{ fontSize: '8px', color: 'var(--text-muted)', fontWeight: '600' }}>/10</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Question description */}
              <div className="mb-4">
                <label style={{ fontSize: '11px' }}>QUESTION PROMPT</label>
                <div style={{ background: 'rgba(0,0,0,0.2)', padding: '14px 18px', borderRadius: '8px', border: '1px solid var(--glass-border)', fontSize: '14px', lineHeight: '1.5', color: 'var(--text-muted)' }}>
                  {selectedAttempt.questionId?.description}
                </div>
              </div>

              {/* Candidate's answer */}
              <div className="mb-4">
                <label style={{ fontSize: '11px' }}>YOUR SUBMISSION</label>
                <div style={{ background: 'rgba(0,0,0,0.3)', padding: '14px 18px', borderRadius: '8px', border: '1px solid var(--glass-border)', fontSize: '14px', lineHeight: '1.5', whiteSpace: 'pre-wrap', maxHeight: '150px', overflowY: 'auto' }}>
                  {selectedAttempt.answerText}
                </div>
              </div>

              {/* Strengths & Weaknesses */}
              {selectedAttempt.feedback && (
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '20px' }}>
                  <div>
                    <h4 style={{ fontSize: '13px', color: '#ffffff', margin: '0 0 8px 0' }}>💪 STRENGTHS</h4>
                    <div className="pill-list">
                      {selectedAttempt.feedback.strengths?.map((s, i) => (
                        <span key={i} className="pill-item pill-item-strength" style={{ width: '100%', display: 'block', fontSize: '12px' }}>
                          ✅ {s}
                        </span>
                      ))}
                    </div>
                  </div>

                  <div>
                    <h4 style={{ fontSize: '13px', color: '#f87171', margin: '0 0 8px 0' }}>⚠️ WEAKNESSES</h4>
                    <div className="pill-list">
                      {selectedAttempt.feedback.weaknesses?.map((w, i) => (
                        <span key={i} className="pill-item pill-item-weakness" style={{ width: '100%', display: 'block', fontSize: '12px' }}>
                          ❌ {w}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {/* Suggestions */}
              {selectedAttempt.feedback?.improvementSuggestions && selectedAttempt.feedback.improvementSuggestions.length > 0 && (
                <div style={{ marginBottom: '24px', borderTop: '1px solid var(--glass-border)', paddingTop: '16px' }}>
                  <h4 style={{ fontSize: '13px', color: '#ffffff', margin: '0 0 8px 0' }}>💡 SUGGESTED IMPROVEMENTS</h4>
                  <ul style={{ paddingLeft: '20px', margin: 0, color: 'var(--text-muted)', fontSize: '13.5px', lineHeight: '1.6' }}>
                    {selectedAttempt.feedback.improvementSuggestions.map((s, i) => (
                      <li key={i} style={{ marginBottom: '6px' }}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Close Button */}
              <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '20px' }}>
                <button className="btn-primary" onClick={() => setSelectedAttempt(null)} style={{ padding: '8px 24px' }}>
                  Close Report
                </button>
              </div>

            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default History;
